### PR TITLE
Added one-to-many example

### PR DESCRIPTION
**Pull request by avermeulen**
@SteveBarnett I added a 1 to many example to the CRUD app as ppl always asked about the dropdowns and I thought an example is needed.

I changed the layout as well. A bit this menu is not sooper but works a spruce of basic navigation CSS would do wonders.

### CODE REVIEW

**Comment by SteveBarnett** [comment]
Do we want to add brief instructions for updating from the previous version of this example? When I tried this I got a unknown field `category_id` error.

Something like:

> If you already have a products table and it doesn't have a `category_id` column, run this SQL to add it:
> 
> ```
> ALTER TABLE products ADD category_id INT;
> ```

**Comment by SteveBarnett** [comment]
@avermeulen: I have added some new colours, based on a goldfish. Yes, really. :)

**Comment by avermeulen** [comment]
@SteveBarnett please review and merge if :+1:

**Comment by avermeulen** [comment]
Why the goldfish? Why is it called that...

**Comment by SteveBarnett** [comment]
@avermeulen the colours are based off a picture of a goldfish :).

**Pull request merged**
